#!/bin/bash
#
##### Script de génération du fichier de correspondance NOM;IP;MAC #####
#
# Auteur : Stephane Boireau (Bernay/Pont-Audemer (27))
#
## $Id$ ##
# modifié par Marc Bansse pour générer l'inventaire simple dans le script /tftpboot/pxelinux.cfg/clonezilla-auto/inventaire/

if [ "$1" = "--help" -o "$1" = "-h" ]; then
	echo "Script permettant de générer un fichier de correspondances NOM;IP;MAC pour"
	echo "l'outil de post-clonage."
	echo ""
	echo "Usage : Pas d'option."
	exit
fi


dest=/tftpboot/pxelinux.cfg/clonezilla-auto/inventaire/

fich_nom_ip_mac="$dest/inventaire.csv"

BASE=$(grep "^BASE" /etc/ldap/ldap.conf | cut -d" " -f2 )
ldapsearch -xLLL -b ou=computers,$BASE cn | grep ^cn | cut -d" " -f2 | while read nom
do
	if [ ! -z $(echo ${nom:0:1} | sed -e "s/[0-9]//g") ]; then
		# PB: on récupère les cn des entrées machines aussi (xpbof et xpbof$)
		ip=$(ldapsearch -xLLL -b ou=computers,$BASE cn=$nom ipHostNumber | grep ipHostNumber | cut -d" " -f2)
		mac=$(ldapsearch -xLLL -b ou=computers,$BASE cn=$nom macAddress | grep macAddress | cut -d" " -f2)

		if [ ! -z "$ip" -a ! -z "$mac" ]; then
			echo "$ip;$nom;$mac" >> $fich_nom_ip_mac
			
		fi
	fi
done

# Conversion en fichier DOS.
#sort ${fich_nom_ip_mac} > ${fich_nom_ip_mac}.tmp
#cat ${fich_nom_ip_mac}.tmp | perl -pe 's/\n/\r\n/' > $fich_nom_ip_mac
#rm -f ${fich_nom_ip_mac}.tmp


echo "Les fichiers ont été générés dans $dest"
echo "Terminé."
